apiVersion: apps/v1
kind: Deployment
metadata:
  name: kudis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kudis
  template:
    metadata:
      labels:
        app: kudis
    spec:
      containers:
        - name: app
          image: kudis
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: my-redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: kudis
spec:
  selector:
    app: kudis
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
