apiVersion: apps/v1
kind: Deployment
metadata:
  name: kudis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kudis
  template:
    metadata:
      labels:
        app: kudis
    spec:
      containers:
        - name: app
          image: saphidev/kudis:2.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: my-redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  timeoutSec: 40
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 0
---
apiVersion: v1
kind: Service
metadata:
  name: kudis
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"my-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: kudis
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: kudis
          servicePort: 80
